### ISSUE TITLE
Block not processed with v0.34.7

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big_dipper#147]
I have updated the node to v0.34.7 and the blocks are not processed after that. Here is the log

```
App 3631 output: { Error: failed [500] {"error":"{\"codespace\":\"sdk\",\"code\":1,\"message\":\"failed to parse params: UnmarshalJSON cannot decode empty bytes\"}"}
App 3631 output:     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
App 3631 output:     at Request._callback (packages/http.js:140:24)
App 3631 output:     at Request.self.callback (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
App 3631 output:     at emitTwo (events.js:126:13)
App 3631 output:     at Request.emit (events.js:214:7)
App 3631 output:     at Request.<anonymous> (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
App 3631 output:     at emitOne (events.js:116:13)
App 3631 output:     at Request.emit (events.js:211:7)
App 3631 output:     at IncomingMessage.<anonymous> (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
App 3631 output:     at Object.onceWrapper (events.js:313:30)
App 3631 output:     at emitNone (events.js:111:20)
App 3631 output:     at IncomingMessage.emit (events.js:208:7)
App 3631 output:     at endReadableNT (_stream_readable.js:1064:12)
App 3631 output:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
App 3631 output:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
App 3631 output:   response: 
App 3631 output:    { statusCode: 500,
App 3631 output:      content: '{"error":"{\\"codespace\\":\\"sdk\\",\\"code\\":1,\\"message\\":\\"failed to parse params: UnmarshalJSON cannot decode empty bytes\\"}"}',
App 3631 output:      headers: 
App 3631 output:       { 'content-type': 'application/json',
App 3631 output:         'x-server-time': '1562215666',
App 3631 output:         date: 'Thu, 04 Jul 2019 04:47:46 GMT',
App 3631 output:         'content-length': '126',
App 3631 output:         connection: 'close' },
App 3631 output:      data: 
App 3631 output:       { error: '{"codespace":"sdk","code":1,"message":"failed to parse params: UnmarshalJSON cannot decode empty bytes"}' } } }
App 3631 output: { Error: failed [500] {"error":"{\"codespace\":\"sdk\",\"code\":1,\"message\":\"failed to parse params: UnmarshalJSON cannot decode empty bytes\"}"}
App 3631 output:     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
App 3631 output:     at Request._callback (packages/http.js:140:24)
App 3631 output:     at Request.self.callback (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
App 3631 output:     at emitTwo (events.js:126:13)
App 3631 output:     at Request.emit (events.js:214:7)
App 3631 output:     at Request.<anonymous> (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
App 3631 output:     at emitOne (events.js:116:13)
App 3631 output:     at Request.emit (events.js:211:7)
App 3631 output:     at IncomingMessage.<anonymous> (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
App 3631 output:     at Object.onceWrapper (events.js:313:30)
App 3631 output:     at emitNone (events.js:111:20)
App 3631 output:     at IncomingMessage.emit (events.js:208:7)
App 3631 output:     at endReadableNT (_stream_readable.js:1064:12)
App 3631 output:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
App 3631 output:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
App 3631 output:   response: 
App 3631 output:    { statusCode: 500,
App 3631 output:      content: '{"error":"{\\"codespace\\":\\"sdk\\",\\"code\\":1,\\"message\\":\\"failed to parse params: UnmarshalJSON cannot decode empty bytes\\"}"}',
App 3631 output:      headers: 
App 3631 output:       { 'content-type': 'application/json',
App 3631 output:         'x-server-time': '1562215666',
App 3631 output:         date: 'Thu, 04 Jul 2019 04:47:46 GMT',
App 3631 output:         'content-length': '126',
App 3631 output:         connection: 'close' },
App 3631 output:      data: 
App 3631 output:       { error: '{"codespace":"sdk","code":1,"message":"failed to parse params: UnmarshalJSON cannot decode empty bytes"}' } } }
App 3631 output: { Error: failed [500] {"error":"{\"codespace\":\"sdk\",\"code\":1,\"message\":\"failed to parse params: UnmarshalJSON cannot decode empty bytes\"}"}
App 3631 output:     at Object.exports.makeErrorByStatus (packages/http.js:176:10)
App 3631 output:     at Request._callback (packages/http.js:140:24)
App 3631 output:     at Request.self.callback (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:185:22)
App 3631 output:     at emitTwo (events.js:126:13)
App 3631 output:     at Request.emit (events.js:214:7)
App 3631 output:     at Request.<anonymous> (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1161:10)
App 3631 output:     at emitOne (events.js:116:13)
App 3631 output:     at Request.emit (events.js:211:7)
App 3631 output:     at IncomingMessage.<anonymous> (/var/www/gaia-13k3.bigdipper.live/bundle/programs/server/npm/node_modules/meteor/http/node_modules/request/request.js:1083:12)
App 3631 output:     at Object.onceWrapper (events.js:313:30)
App 3631 output:     at emitNone (events.js:111:20)
App 3631 output:     at IncomingMessage.emit (events.js:208:7)
App 3631 output:     at endReadableNT (_stream_readable.js:1064:12)
App 3631 output:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
App 3631 output:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
App 3631 output:   response: 
App 3631 output:    { statusCode: 500,
App 3631 output:      content: '{"error":"{\\"codespace\\":\\"sdk\\",\\"code\\":1,\\"message\\":\\"failed to parse params: UnmarshalJSON cannot decode empty bytes\\"}"}',
App 3631 output:      headers: 
App 3631 output:       { 'content-type': 'application/json',
App 3631 output:         'x-server-time': '1562215666',
App 3631 output:         date: 'Thu, 04 Jul 2019 04:47:46 GMT',
App 3631 output:         'content-length': '126',
App 3631 output:         connection: 'close' },
App 3631 output:      data: 
App 3631 output:       { error: '{"codespace":"sdk","code":1,"message":"failed to parse params: UnmarshalJSON cannot decode empty bytes"}' } } }
```

**Comment by kwunyeung** [comment]
Forgot to update gaiacli...
