### ISSUE TITLE
TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by kraymond37** [forbole/big_dipper#203]
Followed instructons to deploy, got an error.
```
$ PORT=3000 ROOT_URL="http://localhost" MONGO_URL="mongodb://localhost:27017/meteor" node main.js 

/home/connor/code/output/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						^

TypeError: Cannot read property 'toLowerCase' of undefined
    at coins.js (both/utils/coins.js:19:60)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at require (packages/modules-runtime.js:258:21)
    at /home/connor/code/output/bundle/programs/server/app/app.js:4808:1
    at /home/connor/code/output/bundle/programs/server/boot.js:419:36
    at Array.forEach (<anonymous>)
    at /home/connor/code/output/bundle/programs/server/boot.js:228:19
    at /home/connor/code/output/bundle/programs/server/boot.js:479:5
    at Function.run (/home/connor/code/output/bundle/programs/server/profile.js:510:12)
    at /home/connor/code/output/bundle/programs/server/boot.js:478:11
```

**Comment by kwunyeung** [comment]
May you share your `settings.json`?

**Comment by kraymond37** [comment]
@kwunyeung 
```
{
    "public":{
        "chainName": "ZChain Testnet",
        "chainId": "zchain-test",
        "gtm": "{Add your Google Tag Manager ID here}",
        "slashingWindow": 10000,
        "uptimeWindow": 250,
        "initialPageSize": 30,
        "bech32PrefixAccAddr": "cosmos",
        "bech32PrefixAccPub": "cosmospub",
        "bech32PrefixValAddr": "cosmosvaloper",
        "bech32PrefixValPub": "cosmosvaloperpub",
        "bech32PrefixConsAddr": "cosmosvalcons",
        "bech32PrefixConsPub": "cosmosvalconspub",
        "stakingDenom": "ZC",
        "mintingDenom": "zcoin",
        "stakingFraction": 1000000,
        "gasPrice": 0.02,
        "coingeckoId": "cosmos"
    },
    "genesisFile": "http://127.0.0.1:8000/genesis.json",
    "remote":{
        "rpc":"http://127.0.0.1:26657",
        "lcd":"http://127.0.0.1:1317"
    },
    "debug": {
        "startTimer": true,
        "readGenesis": true
    },
    "params":{
        "startHeight": 0,
        "defaultBlockTime": 5000,
        "blockInterval": 15000,
        "consensusInterval": 1000,
        "statusInterval":7500,
        "signingInfoInterval": 1800000,
        "proposalInterval": 5000,
        "missedBlocksInterval": 60000,
        "delegationInterval": 900000
    }
}
```
And after deploying, I saw them in `bundle/programs/server/app/app.js`

**Comment by kwunyeung** [comment]
I see. You have to set the `settings.json` in an environment variable. 

https://docs.meteor.com/environment-variables.html#METEOR-SETTINGS
