### ISSUE TITLE
Installation fails because of fibers@3.1.1

### ISSUE THREAD

**Issue by lacabra** [forbole/big_dipper#281]
**Describe the bug**
Following the installation instructions on the README, installation fails because of dependency `fibers@3.1.1`:

```
$ meteor npm install

> fibers@3.1.1 install ~/big_dipper/node_modules/fibers
> node build.js || nodejs build.js

  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:68:2: error: unknown type name 'Handle'
        Handle<String> NewLatin1String(Isolate* isolate, const char* string) {
        ^
../src/fibers.cc:68:8: error: expected unqualified-id
        Handle<String> NewLatin1String(Isolate* isolate, const char* string) {
              ^
../src/fibers.cc:72:2: error: unknown type name 'Handle'
        Handle<String> NewLatin1Symbol(Isolate* isolate, const char* string) {
        ^
../src/fibers.cc:72:8: error: expected unqualified-id
        Handle<String> NewLatin1Symbol(Isolate* isolate, const char* string) {
              ^
../src/fibers.cc:94:2: error: unknown type name 'Handle'
        Handle<Object> NewInstance(Isolate* isolate, Local<Function> fn, int argc, Local<Value> argv[]) {
        ^
../src/fibers.cc:94:8: error: expected unqualified-id
        Handle<Object> NewInstance(Isolate* isolate, Local<Function> fn, int argc, Local<Value> argv[]) {
              ^
../src/fibers.cc:104:2: error: unknown type name 'Handle'
        Handle<Number> ToNumber(Local<Value> value) {
        ^
../src/fibers.cc:104:8: error: expected unqualified-id
        Handle<Number> ToNumber(Local<Value> value) {
              ^
../src/fibers.cc:114:50: error: unknown type name 'Handle'
        Local<Value> GetStackTrace(TryCatch* try_catch, Handle<Context> context) {
                                                        ^
../src/fibers.cc:114:56: error: expected ')'
        Local<Value> GetStackTrace(TryCatch* try_catch, Handle<Context> context) {
                                                              ^
../src/fibers.cc:114:28: note: to match this '('
        Local<Value> GetStackTrace(TryCatch* try_catch, Handle<Context> context) {
                                  ^
../src/fibers.cc:115:32: error: use of undeclared identifier 'context'
                return try_catch->StackTrace(context).ToLocalChecked();
                                             ^
../src/fibers.cc:127:39: error: unknown type name 'Handle'
        void fixStackLimit(Isolate* isolate, Handle<Context> context) {
                                             ^
../src/fibers.cc:127:45: error: expected ')'
        void fixStackLimit(Isolate* isolate, Handle<Context> context) {
                                                   ^
../src/fibers.cc:127:20: note: to match this '('
        void fixStackLimit(Isolate* isolate, Handle<Context> context) {
                          ^
../src/fibers.cc:128:19: error: use of undeclared identifier 'context'
                Script::Compile(context, uni::NewLatin1String(isolate, "void 0;")).ToLocalChecked();
                                ^
../src/fibers.cc:128:33: error: no member named 'NewLatin1String' in namespace 'uni'
                Script::Compile(context, uni::NewLatin1String(isolate, "void 0;")).ToLocalChecked();
                                         ~~~~~^
../src/fibers.cc:149:58: error: unknown type name 'Handle'
        void Reset(Isolate* isolate, Persistent<T>& persistent, Handle<T> handle) {
                                                                ^
../src/fibers.cc:149:64: error: expected ')'
        void Reset(Isolate* isolate, Persistent<T>& persistent, Handle<T> handle) {
                                                                      ^
../src/fibers.cc:149:12: note: to match this '('
        void Reset(Isolate* isolate, Persistent<T>& persistent, Handle<T> handle) {
                  ^
../src/fibers.cc:150:29: error: use of undeclared identifier 'handle'
                persistent.Reset(isolate, handle);
                                          ^
../src/fibers.cc:162:7: error: variable has incomplete type 'void'
        void SetInternalPointer(Handle<T> handle, int index, void* val) {
             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (~/.meteor/packages/meteor-tool/.1.9.0.aoqmdf.9052m++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "~/.meteor/packages/meteor-tool/.1.9.0.aoqmdf.9052m++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node" "~/.meteor/packages/meteor-tool/.1.9.0.aoqmdf.9052m++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd ~/big_dipper/node_modules/fibers
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! fibers@3.1.1 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**To Reproduce**
1. As per the README instructions:
```
meteor npm install
```

**Expected behavior**
The install should succeed.

**Desktop (please complete the following information):**
```
$ meteor --version
Meteor 1.9
```

**Additional context**
Upgrading the `fibers` version in `package.json` from `3.1.1` to `4.0.2` fixes this issue.

**Comment by kwunyeung** [comment]
@lacabra we haven't updated the packages with Meteor 1.9, which has been out for 2 weeks, yet. Meteor bundled with it's own `node`. The `node` version bundled in Meteor 1.8.x was `node v8.17.x`. I guess probably this is the issue as you are running with `node v12`. I think if you update the packages, it would look for the correct packages for latest node version.

Try
```
meteor npm update
```

**Comment by lacabra** [comment]
Thanks @kwunyeung. I run `meteor npm update`, and it had no effect for the failed install.

Yes, I confirm Meteor 1.9 comes with `node v12.14.0`, and that was the source of my troubles. 

This only reinforces the need to have a requirements section that specifies which versions need to be installed for this repo to work, as in #274 and expanding it :)

**Comment by kwunyeung** [comment]
Thanks @lacabra . I have just tried Meteor 1.9 and it doesn't update `fibers` itself but yes `4.0.3` is what is it expecting to be used.

https://docs.meteor.com/changelog.html#changes

**Comment by kwunyeung** [comment]
close with #283 merged
